// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ErrorPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsErrorPayload(buf []byte, offset flatbuffers.UOffsetT) *ErrorPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ErrorPayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsErrorPayload(buf []byte, offset flatbuffers.UOffsetT) *ErrorPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ErrorPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ErrorPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ErrorPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ErrorPayload) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrorPayload) ErrorCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrorPayload) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrorPayload) Fatal() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ErrorPayload) MutateFatal(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func ErrorPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ErrorPayloadAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func ErrorPayloadAddErrorCode(builder *flatbuffers.Builder, errorCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(errorCode), 0)
}
func ErrorPayloadAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func ErrorPayloadAddFatal(builder *flatbuffers.Builder, fatal bool) {
	builder.PrependBoolSlot(3, fatal, false)
}
func ErrorPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
