// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IPCMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsIPCMessage(buf []byte, offset flatbuffers.UOffsetT) *IPCMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IPCMessage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsIPCMessage(buf []byte, offset flatbuffers.UOffsetT) *IPCMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IPCMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *IPCMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IPCMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IPCMessage) MessageType() MessageType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return MessageType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *IPCMessage) MutateMessageType(n MessageType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *IPCMessage) Payload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *IPCMessage) PayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *IPCMessage) PayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *IPCMessage) MutatePayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func IPCMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IPCMessageAddMessageType(builder *flatbuffers.Builder, messageType MessageType) {
	builder.PrependInt8Slot(0, int8(messageType), 0)
}
func IPCMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func IPCMessageStartPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func IPCMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
