// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import "strconv"

type LogLevel int8

const (
	LogLevelDEBUG LogLevel = 0
	LogLevelINFO  LogLevel = 1
	LogLevelWARN  LogLevel = 2
	LogLevelERROR LogLevel = 3
)

var EnumNamesLogLevel = map[LogLevel]string{
	LogLevelDEBUG: "DEBUG",
	LogLevelINFO:  "INFO",
	LogLevelWARN:  "WARN",
	LogLevelERROR: "ERROR",
}

var EnumValuesLogLevel = map[string]LogLevel{
	"DEBUG": LogLevelDEBUG,
	"INFO":  LogLevelINFO,
	"WARN":  LogLevelWARN,
	"ERROR": LogLevelERROR,
}

func (v LogLevel) String() string {
	if s, ok := EnumNamesLogLevel[v]; ok {
		return s
	}
	return "LogLevel(" + strconv.FormatInt(int64(v), 10) + ")"
}
