// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsLogPayload(buf []byte, offset flatbuffers.UOffsetT) *LogPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogPayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLogPayload(buf []byte, offset flatbuffers.UOffsetT) *LogPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LogPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LogPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LogPayload) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LogPayload) Level() LogLevel {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return LogLevel(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *LogPayload) MutateLevel(n LogLevel) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *LogPayload) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LogPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LogPayloadAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func LogPayloadAddLevel(builder *flatbuffers.Builder, level LogLevel) {
	builder.PrependInt8Slot(1, int8(level), 0)
}
func LogPayloadAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func LogPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
