// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import "strconv"

type SessionStatus int8

const (
	SessionStatusINITIALIZING     SessionStatus = 0
	SessionStatusCONNECTING_ANAM  SessionStatus = 1
	SessionStatusCONNECTING_AGORA SessionStatus = 2
	SessionStatusCONNECTED        SessionStatus = 3
	SessionStatusSTREAMING        SessionStatus = 4
	SessionStatusDISCONNECTING    SessionStatus = 5
	SessionStatusDISCONNECTED     SessionStatus = 6
	SessionStatusFAILED           SessionStatus = 7
)

var EnumNamesSessionStatus = map[SessionStatus]string{
	SessionStatusINITIALIZING:     "INITIALIZING",
	SessionStatusCONNECTING_ANAM:  "CONNECTING_ANAM",
	SessionStatusCONNECTING_AGORA: "CONNECTING_AGORA",
	SessionStatusCONNECTED:        "CONNECTED",
	SessionStatusSTREAMING:        "STREAMING",
	SessionStatusDISCONNECTING:    "DISCONNECTING",
	SessionStatusDISCONNECTED:     "DISCONNECTED",
	SessionStatusFAILED:           "FAILED",
}

var EnumValuesSessionStatus = map[string]SessionStatus{
	"INITIALIZING":     SessionStatusINITIALIZING,
	"CONNECTING_ANAM":  SessionStatusCONNECTING_ANAM,
	"CONNECTING_AGORA": SessionStatusCONNECTING_AGORA,
	"CONNECTED":        SessionStatusCONNECTED,
	"STREAMING":        SessionStatusSTREAMING,
	"DISCONNECTING":    SessionStatusDISCONNECTING,
	"DISCONNECTED":     SessionStatusDISCONNECTED,
	"FAILED":           SessionStatusFAILED,
}

func (v SessionStatus) String() string {
	if s, ok := EnumNamesSessionStatus[v]; ok {
		return s
	}
	return "SessionStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
