// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StartSessionPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsStartSessionPayload(buf []byte, offset flatbuffers.UOffsetT) *StartSessionPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StartSessionPayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStartSessionPayload(buf []byte, offset flatbuffers.UOffsetT) *StartSessionPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StartSessionPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StartSessionPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StartSessionPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StartSessionPayload) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) AppId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) Channel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) BotUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StartSessionPayload) MutateBotUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *StartSessionPayload) BotToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) PalabraUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StartSessionPayload) MutatePalabraUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *StartSessionPayload) AnamApiKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) AnamBaseUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) AnamAvatarId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) AnamUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StartSessionPayload) MutateAnamUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *StartSessionPayload) AnamToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSessionPayload) TargetLanguage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StartSessionPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func StartSessionPayloadAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func StartSessionPayloadAddAppId(builder *flatbuffers.Builder, appId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(appId), 0)
}
func StartSessionPayloadAddChannel(builder *flatbuffers.Builder, channel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(channel), 0)
}
func StartSessionPayloadAddBotUid(builder *flatbuffers.Builder, botUid uint32) {
	builder.PrependUint32Slot(3, botUid, 0)
}
func StartSessionPayloadAddBotToken(builder *flatbuffers.Builder, botToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(botToken), 0)
}
func StartSessionPayloadAddPalabraUid(builder *flatbuffers.Builder, palabraUid uint32) {
	builder.PrependUint32Slot(5, palabraUid, 0)
}
func StartSessionPayloadAddAnamApiKey(builder *flatbuffers.Builder, anamApiKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(anamApiKey), 0)
}
func StartSessionPayloadAddAnamBaseUrl(builder *flatbuffers.Builder, anamBaseUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(anamBaseUrl), 0)
}
func StartSessionPayloadAddAnamAvatarId(builder *flatbuffers.Builder, anamAvatarId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(anamAvatarId), 0)
}
func StartSessionPayloadAddAnamUid(builder *flatbuffers.Builder, anamUid uint32) {
	builder.PrependUint32Slot(9, anamUid, 0)
}
func StartSessionPayloadAddAnamToken(builder *flatbuffers.Builder, anamToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(anamToken), 0)
}
func StartSessionPayloadAddTargetLanguage(builder *flatbuffers.Builder, targetLanguage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(targetLanguage), 0)
}
func StartSessionPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
