// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StatusPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusPayload(buf []byte, offset flatbuffers.UOffsetT) *StatusPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusPayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStatusPayload(buf []byte, offset flatbuffers.UOffsetT) *StatusPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StatusPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusPayload) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatusPayload) Status() SessionStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return SessionStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StatusPayload) MutateStatus(n SessionStatus) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *StatusPayload) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StatusPayload) AnamUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusPayload) MutateAnamUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func StatusPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StatusPayloadAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func StatusPayloadAddStatus(builder *flatbuffers.Builder, status SessionStatus) {
	builder.PrependInt8Slot(1, int8(status), 0)
}
func StatusPayloadAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func StatusPayloadAddAnamUid(builder *flatbuffers.Builder, anamUid uint32) {
	builder.PrependUint32Slot(3, anamUid, 0)
}
func StatusPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
