// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StopSessionPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsStopSessionPayload(buf []byte, offset flatbuffers.UOffsetT) *StopSessionPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StopSessionPayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStopSessionPayload(buf []byte, offset flatbuffers.UOffsetT) *StopSessionPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StopSessionPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StopSessionPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StopSessionPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StopSessionPayload) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StopSessionPayload) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StopSessionPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StopSessionPayloadAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func StopSessionPayloadAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reason), 0)
}
func StopSessionPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
