// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package botipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SwitchAudioSourcePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsSwitchAudioSourcePayload(buf []byte, offset flatbuffers.UOffsetT) *SwitchAudioSourcePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SwitchAudioSourcePayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSwitchAudioSourcePayload(buf []byte, offset flatbuffers.UOffsetT) *SwitchAudioSourcePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SwitchAudioSourcePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SwitchAudioSourcePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SwitchAudioSourcePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SwitchAudioSourcePayload) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SwitchAudioSourcePayload) NewUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SwitchAudioSourcePayload) MutateNewUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SwitchAudioSourcePayload) IsTranslation() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SwitchAudioSourcePayload) MutateIsTranslation(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func SwitchAudioSourcePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SwitchAudioSourcePayloadAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func SwitchAudioSourcePayloadAddNewUid(builder *flatbuffers.Builder, newUid uint32) {
	builder.PrependUint32Slot(1, newUid, 0)
}
func SwitchAudioSourcePayloadAddIsTranslation(builder *flatbuffers.Builder, isTranslation bool) {
	builder.PrependBoolSlot(2, isTranslation, false)
}
func SwitchAudioSourcePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
